import os
import re
import sys
from uuid import uuid4

# Add sdk/python to the path so memtrace can be imported without pip install
sys.path.insert(
    0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "sdk", "python"))
)

from dotenv import load_dotenv
from langchain.agents import create_agent
from langchain.tools import tool
from memtrace import init_tracer, session, shutdown, trace_step, trace_step_context
from memtrace.langchain import MemTraceCallbackHandler

load_dotenv()
# service_name / endpoint / headers come from .env (generated by the dashboard when creating an
# experiment API key, ADR-013) instead of being hardcoded here, so traces land in that experiment.
init_tracer()

# Naive, non-generative checks: no LLM involved, so they aren't auto-instrumented.
# Each one becomes its own span, nested under "input_guardrail" (ADR-026). Using @trace_step
# (not the bare context manager) captures the argument and return value of each check as the
# span's input/output when MEMTRACE_CAPTURE_CONTENT=true, so they show up in the dashboard.
PII_REGEX = re.compile(r"\b\d{3}-\d{2}-\d{4}\b")  # e.g. a US SSN shape
TOXIC_WORDS = {"idiot", "stupid"}


@trace_step(name="guardrail.regex_pii", step_type="guardrail.regex_pii")
def check_regex_pii(user_message: str) -> bool:
    return bool(PII_REGEX.search(user_message))


@trace_step(name="guardrail.toxicity_rules", step_type="guardrail.toxicity_rules")
def check_toxicity_rules(user_message: str) -> bool:
    return any(word in user_message.lower() for word in TOXIC_WORDS)


@trace_step(name="input_guardrail", step_type="chain")
def run_input_guardrail(user_message: str) -> bool:
    """Runs the guardrail's checks as child spans of a parent "input_guardrail" step.

    Returns True if the message should be blocked.
    """
    pii_found = check_regex_pii(user_message)
    is_toxic = check_toxicity_rules(user_message)
    return pii_found or is_toxic


@tool
def search(query: str) -> str:
    """Search for information."""
    return f"Results for: {query}"


agent = create_agent(
    model="google_genai:gemini-2.5-flash",
    tools=[search],
    system_prompt="You are a helpful assistant. Be concise and accurate.",
)

conversation_id = str(uuid4())
config = {
    "configurable": {"thread_id": conversation_id},
    "callbacks": [MemTraceCallbackHandler()],
    "metadata": {
        "thread_id": conversation_id,
    },
}

# OPTION 1: Manual - you control which chains get instrumented
# (recommended for production libraries)
try:
    with session(conversation_id):
        # One parent step for the whole turn: the guardrail and the agent invocation (and
        # everything LangGraph/LangChain create inside it) become spans of the *same* trace,
        # not two separate ones (ADR-026).
        with trace_step_context("conversation_turn", step_type="chain"):
            user_message = "What's the weather in San Francisco?"

            if run_input_guardrail(user_message):
                print("Blocked by the input guardrail.")
            else:
                result = agent.invoke(
                    {"messages": [{"role": "user", "content": user_message}]},
                    config=config,
                )
                print(result)
finally:
    shutdown()
