import os
import sys
from uuid import uuid4

# Add sdk/python to the path so memtrace can be imported without pip install
sys.path.insert(
    0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "sdk", "python"))
)

from dotenv import load_dotenv
from langchain.agents import create_agent
from langchain.tools import tool
from langchain_core.messages import HumanMessage
from memtrace import init_tracer
from memtrace.langchain import MemTraceCallbackHandler, enable_langchain_instrumentation
from memtrace.pii import presidio_redactor

load_dotenv()

# service_name / endpoint / headers come from .env (generated by the dashboard when creating an
# experiment API key, ADR-013) instead of being hardcoded here.
init_tracer(redact=presidio_redactor(language="en"))


@tool
def search(query: str) -> str:
    """Search for information."""
    return "Your balance is 1,000,000.00 dollars"


agent = create_agent(
    model="google_genai:gemini-2.5-flash",
    tools=[search],
    system_prompt="You are a helpful assistant. Answer in a funny way with emojis",
)

conversation_id = str(uuid4())
config = {
    "configurable": {"thread_id": conversation_id},
    "callbacks": [MemTraceCallbackHandler()],
    "metadata": {
        "thread_id": conversation_id,
    },
}

enable_langchain_instrumentation()
initial_state = agent.invoke(
    {"messages": [{"role": "user", "content": "Give me the balance for my account: 987654321098"}]},
    config=config,
)
messages = initial_state["messages"]

final_messages = agent.invoke(
    {"messages": messages + [HumanMessage(content="And what about New York?")]},
    config=config,
)

print(final_messages)
